app/home/forms.py
from wtforms import Form
from wtforms.fields import simple,core,html5
from wtforms import widgets
from wtforms import  validators

from app.models import Admin
from app import models
from app import db


class RegForm(Form):
    name = simple.StringField(
        validators=[
            validators.DataRequired(message='会员昵称不能为空')
        ],
        widget=widgets.TextInput(),
        render_kw={'class': "form-control input-lg", 'placeholder': "请输入会员昵称！",'id':"input_name"}
    )

    pwd = simple.StringField(
        validators=[
            validators.DataRequired(message='密码不能为空')
        ],
        render_kw={'class': "form-control input-lg", 'placeholder': "请输入密码!", 'id': "input_password"},
        widget=widgets.PasswordInput()
    )

    confirmpwd = simple.StringField(
        label='确认密码',
        validators=[
            validators.DataRequired(message='重复密码不能为空'),
            validators.EqualTo('pwd',message='两次输入密码不一致')
        ],
        render_kw={'class': "form-control", 'placeholder': "请输入确认密码!",'id':'input_repassword'},
        widget=widgets.PasswordInput()
    )

    email = html5.EmailField(
        validators=[
            validators.DataRequired(message='邮箱不能为空'),
            validators.Email(message='邮箱格式不正确')
        ],
        widget=widgets.TextInput(),
        render_kw={"class": "form-control input-lg",'placeholder': "请输入邮箱!",'id':"input_email"}
    )

    phone=simple.StringField(
        validators=[
            validators.DataRequired(message='请输入手机号码'),
            validators.Regexp('^[1][3,4,5,7,8][0-9]{9}$',message='手机号码格式不正确')
        ],
        widget=widgets.TextInput(),
        render_kw={'id':"input_phone","class": "form-control input-lg",'placeholder': "请输入手机号码!"}
    )

    def validate_name(self, field):
        count = db.session.query(models.User).filter_by(name=field.data).count()
        if count:
            raise validators.StopValidation('该名称已经被占用')





class LoginForm(Form):
    '''
    会员登录
    '''
    name = simple.StringField(
        label='用户名',
        validators=[
            validators.DataRequired(message='用户名不能为空')
        ],
        render_kw={'class': "form-control", 'placeholder': "请输入用户名!",'id':'input_contact'},
        widget=widgets.TextInput()
    )

    pwd = simple.PasswordField(
        label='密码',
        validators=[
            validators.DataRequired(message='密码不能为空')
        ],
        render_kw={'class': "form-control", 'placeholder': "请输入密码!",'id':'input_password'},
        widget=widgets.TextInput()
    )

    def validate_name(self, field):
        name = field.data
        print(name, '-----')
        count =models.User.query.filter_by(name=name).count()
        if count == 0:
            raise validators.StopValidation('用户名不存在')



class UserForm(Form):
    name = simple.StringField(
        validators=[
            validators.DataRequired(message='会员昵称不能为空')
        ],
        widget=widgets.TextInput(),
        render_kw={'class': "form-control input-lg", 'placeholder': "请输入会员昵称！", 'id': "input_name"}
    )

    email = html5.EmailField(
        validators=[
            validators.DataRequired(message='邮箱不能为空'),
            validators.Email(message='邮箱格式不正确')
        ],
        widget=widgets.TextInput(),
        render_kw={"class": "form-control input-lg", 'placeholder': "请输入邮箱!", 'id': "input_email"}
    )

    phone = simple.StringField(
        validators=[
            validators.DataRequired(message='请输入手机号码'),
            validators.Regexp('^[1][3,4,5,7,8][0-9]{9}$', message='手机号码格式不正确')
        ],
        widget=widgets.TextInput(),
        render_kw={'id': "input_phone", "class": "form-control input-lg", 'placeholder': "请输入手机号码!"}
    )

    avatar=simple.FileField(
        label='头像',
        validators=[
            validators.DataRequired(message='头像不能为空')
        ],
        widget=widgets.FileInput(),
        render_kw={'id':"avatar_file"}

    )
    info = simple.TextAreaField(
        label='简介',
        validators={
            validators.DataRequired(message='简介不能为空')
        },
        widget=widgets.TextArea(),
        render_kw={'class': "form-control", 'rows': "10", 'id': "input_info"}
    )

class PwdForm(Form):
    oldpwd = simple.StringField(
        label='旧密码',
        validators=[
            validators.DataRequired(message='旧密码不能为空')
        ],
        widget=widgets.PasswordInput(),
        render_kw={'class': "form-control", 'id': "input_oldpwd", 'placeholder': "请输入旧密码！"}
    )

    newpwd = simple.StringField(
        label='新密码',
        validators=[
            validators.DataRequired(message='新密码不能为空')
        ],
        widget=widgets.PasswordInput(),
        render_kw={'class': "form-control", 'id': "input_newpwd", 'placeholder': "请输入新密码！"}
    )

app/home/__init__.py
#coding:utf8
from flask import Blueprint
home=Blueprint("home",__name__)

from app.home import views

app/home/views.py
# coding:utf8
import os
import json

from . import home
from flask import render_template, redirect, url_for, request, session
from werkzeug.utils import secure_filename

from .forms import RegForm, LoginForm, UserForm, PwdForm
from app import models
from  app import db
from app.utils.pager import Pagination

BASEDIR = os.path.abspath(os.path.dirname(__file__)).strip('\home')
print(BASEDIR)

file_dir = os.path.join(BASEDIR, 'static', 'avatar')

if not os.path.exists(file_dir):
    os.makedirs(file_dir)


@home.before_request
def check_is_login():
    '''
    检测是否登录了
    :return:
    '''
    if request.path == '/login/':
        return None
    if request.path == '/logout/':
        return None
    if request.path == '/regist/':
        return None
    if request.path=='/':
        return  None
    if session.get('user'):
        return None
    if not session.get('user'):
        return redirect(url_for('home.login'))




def getUser():
    '''
    获取当前登录的会员
    :return:
    '''
    username = session.get('user')
    user = db.session.query(models.User).filter_by(name=username).first()
    return user


@home.route("/")
def index():
    '''
    首页
    :return:
    '''
    previews = db.session.query(models.Preview).all()
    tags=db.session.query(models.Tag).all()
    tid=request.args.get("tid",0)
    star=request.args.get("star",0)
    time=request.args.get("time",0)
    pm=request.args.get("pm",0)
    cm=request.args.get("cm",0)
    p=dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm
    )
    movies=None
    if int(tid)!=0 and int(star)==0:
       movies=db.session.query(models.Movie).filter_by(tag_id=int(tid)).all()
       print(movies,'---------')
    if int(star)!=0 and int(tid)==0:
        movies=db.session.query(models.Movie).filter_by(star=int(star)).all()
    if int(star) != 0 and int(tid) != 0:
        movies = db.session.query(models.Movie).filter_by(star=int(star),tag_id=int(tid)).all()
    if int(tid)==0 and int(star)==0:
        movies=db.session.query(models.Movie).all()
    current_page = request.args.get('page', 1)
    total_count = len(movies)
    base_url = request.path
    parmas = request.args.to_dict()
    pageObj = Pagination(current_page, total_count, base_url, parmas)
    movies = movies[pageObj.start:pageObj.end]

    return render_template('/home/index.html',previews=previews,tags=tags,p=p,movies=movies,pageObj=pageObj)


@home.route('/login/', methods=['GET', 'POST'])
def login():
    '''
    会员登录
    :return:
    '''
    if request.method == 'POST':
        form = LoginForm(request.form)
        if form.validate():
            data = form.data
            user = db.session.query(models.User).filter_by(name=data.get('name'), pwd=data.get('pwd')).first()
            if user:
                session['user'] = data.get('name')
                user = getUser()
                userlog = models.Userlog(ip=request.remote_addr, user_id=user.id)
                db.session.add(userlog)
                db.session.commit()
                return redirect(url_for('home.index'))
            else:
                msg = '密码错误'
                return render_template('home/login.html', form=form, msg=msg)
        return render_template('home/login.html', form=form)
    form = LoginForm()
    return render_template('home/login.html', form=form)


@home.route('/logout/')
def logout():
    '''
    会员注销
    :return:
    '''
    session['user'] = ''
    return redirect(url_for('home.login'))


@home.route('/regist/', methods=['GET', 'POST'])
def regist():
    '''
    会员注册
    :return:
    '''
    if request.method == 'POST':
        form = RegForm(request.form)
        if form.validate():
            data = form.data
            user = models.User(
                name=data.get('name'),
                pwd=data.get('pwd'),
                email=data.get('email'),
                phone=data.get('phone')
            )
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('home.login'))
        return render_template('/home/register.html', form=form)
    form = RegForm()
    return render_template('/home/register.html', form=form)


@home.route('/user/', methods=['GET', 'POST'])
def user():
    '''
    用户信息展示
    :return:
    '''
    if request.method == 'POST':
        form = UserForm(request.form)
        file = request.files['avatar']
        filename = secure_filename(file.filename)
        file.save(os.path.join(file_dir, filename))
        data = form.data
        avatar = data.get('avatar')
        user = getUser()
        db.session.query(models.User).filter_by(id=user.id).update({
            'name': data.get('name'),
            'pwd': data.get('pwd'),
            'email': data.get('email'),
            'phone': data.get('phone'),
            'avatar': data.get(avatar),
            'info': data.get('info')
        })
        db.session.commit()
        return redirect(url_for('home.user'))
    user = getUser()
    form = UserForm(
        data={'name': user.name, 'email': user.email, 'phone': user.phone, 'avatar': user.avatar, 'info': user.info})
    return render_template('/home/user.html', form=form)


@home.route('/changpwd/', methods=['GET', 'POST'])
def changpwd():
    '''
       修改密码
       :return:
       '''
    if request.method == 'POST':
        form = PwdForm(request.form)
        if form.validate():
            oldpwd = form.data.get('oldpwd')
            user = db.session.query(models.User).filter_by(pwd=oldpwd).first()
            if user:
                username = session.get('user')
                db.session.query(models.User).filter_by(name=username).update({'pwd': form.data.get('newpwd')})
                db.session.commit()
                session['user'] = ''
                return redirect(url_for('home.login'))
            else:
                msg = '旧密码输入错误'
                return render_template('/home/changpwd.html', form=form, msg=msg)
        return render_template('/home/changpwd.html', form=form)
    form = PwdForm()
    return render_template('/home/changpwd.html', form=form)


@home.route('/comments/')
def comments():
    '''
    展示当前登录用户的评论
    :return:
    '''
    user=getUser()
    comments=db.session.query(models.Comment).join(models.User).filter(models.Comment.user_id==models.User.id).filter(models.User.id==user.id)
    return render_template('/home/comments.html',comments=comments)

@home.route('/search/')
def search():
    '''
    根据电影名称搜索电影并实现分页和计数
    :return:
    '''
    key=request.args.get('key',0)
    movies=db.session.query(models.Movie).filter(models.Movie.title.like('{}%'.format(key))).all()
    current_page = request.args.get('page', 1)
    total_count = len(movies)
    base_url = request.path
    parmas = request.args.to_dict()
    pageObj = Pagination(current_page, total_count, base_url, parmas)
    movies = movies[pageObj.start:pageObj.end]
    return render_template('/home/search.html',key=key,movies=movies,pageObj=pageObj,total_count=total_count)

@home.route('/loginlog/')
def loginlog():
    userlogs=db.session.query(models.Userlog).all()
    return render_template('/home/loginlog.html',userlogs=userlogs)


@home.route('/moviecol/')
def moviecol():
    return render_template('/home/moviecol.html')

@home.route('/play/<int:id>')
def play(id):
    movie=db.session.query(models.Movie).filter_by(id=id).first()
    # commits=db.session.query(models.Comment).filter_by()
    return render_template('/home/play.html',movie=movie)
@home.route('/movieComment/<int:id>',methods=['GET', 'POST'])
def movieComment(id):
    '''
    电影评论
    :param id:
    :return:
    '''
    content=request.form.get('content')
    response={'status':False,'msg':'','content':'','addtime':''}
    user=getUser()
    if  content:
        comment=models.Comment(content=content,user_id=user.id,movie_id=id)
        db.session.add(comment)
        db.session.commit()
        response['msg']='添加成功'
        response['status']=True
        response['content']=comment.content
        response['addtime']=str(comment.addtime)
    else:
        response['msg']='不能提交空内容'

    print(content)

    return json.dumps(response)

app/templates/home/animation.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>热映电影</title>
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/style.css')}}">
</head>
<body>
<!--轮播图 开始 -->
<div class="main_banner">
	<div class="main_banner_wrap">
		<canvas id="myCanvas" width="150" height="150"></canvas>
		<div class="main_banner_box" id="m_box">
			<a href="javascript:void(0)" class="banner_btn js_pre">
				<span class="banner_btn_arrow"><i></i></span>
			</a>
			<a href="javascript:void(0)" class="banner_btn btn_next js_next">
				<span class="banner_btn_arrow"><i></i></span>
			</a>
			<ul>
				{% for p in previews %}
				<li id="imgCard{{loop.index-1}}">
					<a href=""><span style="opacity:0;"></span></a>
					<!--<img src="{{url_for('static',filename='logo/{{p.logo}')}}" alt="">-->
					<img src="{{url_for('static',filename='logo/'+p.logo)}}" alt="">
					<p style="bottom:0">{{p.title}}</p>
				</li>
				{%endfor%}
				<!--<li id="imgCard1">-->
					<!--<a href=""><span style="opacity:0.4;"></span></a>      -->
					<!--<img src="{{url_for('static',filename='main_banner/big0120150101183428.jpg')}}" alt="">-->
					<!--<p>乐侃有声节目第二期</p>-->
				<!--</li> -->
				<!--<li id="imgCard2">-->
					<!--<a href=""><span style="opacity:0.4;" ></span></a>        -->
					<!--<img src="{{url_for('static',filename='main_banner/big0320150101183351.jpg')}}" alt="">-->
					<!--<p>乐见大牌：”荣“耀之声，”维“我独尊</p>-->
				<!--</li> -->
				<!--<li id="imgCard3">-->
					<!--<a href=""><span style="opacity:0.4;"></span></a>      -->
					<!--<img src="{{url_for('static',filename='main_banner/big0420150101224343.jpg')}}" alt="">-->
					<!--<p>王力宏四年心血结晶</p>-->
				<!--</li> -->
				<!--<li id="imgCard4">-->
					<!--<a href=""><span style="opacity:0.4;"></span></a>      -->
					<!--<img src="{{url_for('static',filename='main_banner/big0720150102210934.jpg')}}" alt="">-->
					<!--<p>MV精选：《武媚》女神团美艳大比拼</p>-->
				<!--</li> -->
			</ul>
			<!--火狐倒影图层-->
			<p id="rflt"></p>
			<!--火狐倒影图层-->
		</div>
		<!--序列号按钮-->
		<div class="btn_list">
			<span class="curr"></span><span></span><span></span><span></span><span></span>
		</div>
	</div>

</div>
<!--轮播图 结束 -->

<script type="text/javascript" src="{{url_for('static',filename='js/jquery.js')}}"></script>
<script type="text/javascript" src="{{url_for('static',filename='js/script.js')}}"></script>

</body>
</html>

app/templates/home/changpwd.html
{% extends 'home/home.html' %}


{% block css %}
<style>
 .col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9{
            padding-right: 3px;
            padding-left: 3px;
        }
 </style>
{% endblock %}


{% block content%}
{% include 'home/menu.html'%}
   <div class="col-md-9">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;会员中心</h3>
            </div>
            <div class="panel-body">
                <form role="form" method="post">
                    <fieldset>
                            <div class="form-group">
                                <label for="input_oldpwd"><span class="glyphicon glyphicon-lock"></span>&nbsp;旧密码</label>
                                {{form.oldpwd}}
                                {{form.oldpwd.errors[0]}}
                                <!--<input id="input_oldpwd" class="form-control" placeholder="旧密码" name="oldpwd" type="password" autofocus>-->
                            </div>
                            <div class="col-md-12" id="error_oldpwd"></div>
                            <div class="form-group">
                                <label for="input_newpwd"><span class="glyphicon glyphicon-lock"></span>&nbsp;新密码</label>
                                {{form.newpwd}}
                                {{form.newpwd.errors[0]}}
                                <!--<input id="input_newpwd" class="form-control" placeholder="新密码" name="newpwd" type="password" autofocus>-->
                            </div>
                        {{msg}}
                            <div class="col-md-12" id="error_newpwd"></div>
                            <button  class="btn btn-success"><span class="glyphicon glyphicon-edit"></span>&nbsp;修改密码</button>
                        </fieldset>
                </form>
            </div>
        </div>
    </div>
{%endblock%}


{%block js%}
<script>
    (function () {
      $('#m_2').addClass('active')
    })()
</script>
{% endblock%}

app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='base/images/logo.png')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='base/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='base/css/bootstrap-movie.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='base/css/animate.css')}}">
    <style>
        .navbar-brand>img {
            display: inline;
        }

    </style>
    <style>
        .media{
            padding:3px;
            border:1px solid #ccc
        }

    </style>
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{url_for('home.index')}}" class="navbar-brand" style="width:250px;">
                <img src="{{url_for('static',filename='base/images/logo.png')}}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" id="input_movie" placeholder="请输入电影名！">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="search_btn" ><span class="glyphicon glyphicon-search" ></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{url_for('home.index')}}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.login')}}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.regist')}}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.logout')}}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.user')}}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}

    {% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{url_for('static',filename='base/js/jquery.min.js')}}"></script>
<script src="{{url_for('static',filename='base/js/bootstrap.min.js')}}"></script>
<script src="{{url_for('static',filename='base/js/jquery.singlePageNav.min.js')}}"></script>
<script src="{{url_for('static',filename='base/js/wow.min.js')}}"></script>
<script src="{{url_for('static',filename='lazyload/jquery.lazyload.min.js')}}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });
     $("#search_btn").click(function () {

            var key=$('#input_movie').val();

            location.href="{{url_for('home.search')}}?key="+key
        })
</script>




{%block js%}{%endblock%}
</body>
</html>

app/templates/home/index.html
{%extends 'home/home.html' %}

{% block content%}
<!--导航-->
<!--内容-->
<!--内容-->
<!--热门电影-->
<section id="hotmovie" style="margin-top:76px">
    <div class="container">
        <div class="row wow fadeInRight" data-wow-delay="0.6s">
            <div class="row">
                <!--<iframe class="wow fadeIn" width="100%" height="375px" frameborder=0 scrolling=no src="home/animation.html"></iframe>-->
            {% include 'home/animation.html' %}
            </div>
        </div>
    </div>
</section>
<!--热门电影-->
<!--电影列表-->
<section id="movielist">
    <div class="container">
        <div class="row wow fadeIn" data-wow-delay="0.6s">
            <div class="col-md-12 table-responsive">
                <table class="table text-left table-bordered" id="movietags">
                    <tr>
                        <td style="width:10%;">电影标签</td>
                        <td style="width:90%;">
                            {% for tag in tags %}
                            <a href="{{url_for('home.index')}}?tid={{tag.id}}&star={{p['star']}}&time={{p['time']}}&pm={{p['pm']}}&cm={{p['cm']}}" class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;{{tag.name}}</a>
                            &nbsp;{% endfor %}

                    </tr>
                    <tr>
                        <td>电影星级</td>
                        <td>
                            {%for v in range(1,6) %}
                            <a href="{{url_for('home.index')}}?tid={{p['tid']}}&star={{v}}&time={{p['time']}}&pm={{p['pm']}}&cm={{p['cm']}}" class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;{{v}}星</a>
                            &nbsp;
                           {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td>上映时间</td>
                        <td>
                            <a href="{{url_for('home.index')}}?tid={{p['tid']}}&star={{p['star']}}&time=1&pm={{p['pm']}}&cm={{p['cm']}}" class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;最近</span></a>
                            &nbsp;
                            &nbsp;
                            <a href="{{url_for('home.index')}}?tid={{p['tid']}}&star={{p['star']}}&time=2&pm={{p['pm']}}&cm={{p['cm']}}" class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;更早</span></a>
                        </td>
                    </tr>
                    <tr>
                        <td>播放数量</td>
                        <td>
                            <a href="{{url_for('home.index')}}?tid={{p['tid']}}&star={{p['star']}}&time={{p['time']}}&pm=1&cm={{p['cm']}}" class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span></a>
                            &nbsp;
                            <a href="{{url_for('home.index')}}?tid={{p['tid']}}&star={{p['star']}}&time={{p['time']}}&pm=2&cm={{p['cm']}}" class="label label-danger"><span class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                    <tr>
                        <td>评论数量</td>
                        <td>
                            <a href="{{url_for('home.index')}}?tid={{p['tid']}}&star={{p['star']}}&time={{p['time']}}&pm={{p['pm']}}&cm=1" class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span></a>
                            &nbsp;
                            <a href="{{url_for('home.index')}}?tid={{p['tid']}}&star={{p['star']}}&time={{p['time']}}&pm={{p['pm']}}&cm=2"  class="label label-danger"><span class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                </table>
            </div>
            {% for m in movies %}
            <div class="col-md-3">
                <div class="movielist text-center">
                    <!--<img data-original="holder.js/262x166"
                             class="img-responsive lazy center-block" alt="">-->
                    <img src="holder.js/262x166" class="img-responsive center-block" alt="">
                    <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                        <span style="color:#999;font-style: italic;">{{m.title}}</span><br>
                        <div>
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                            <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                        </div>
                    </div>
                    <a href="{{url_for('home.play',id=m.id)}}" class="btn btn-primary" target="_blank" role="button"><span class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>
        <div class="box-footer clearfix">
                            <ul class="pagination pagination-sm no-margin pull-right">
                                {{ pageObj.page_html()|safe }}
                            </ul>
                        </div>
{% endblock %}

app/templates/home/menu.html
<div class="col-md-3">
        <div class="list-group">
            <a id="m_1" href="{{ url_for('home.user') }}" class="list-group-item ">
                <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
            </a>
             <a id="m_2" href="{{ url_for('home.changpwd') }}" class="list-group-item">
                <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
            </a>
            <a id="m_3" href="{{ url_for('home.comments') }}" class="list-group-item">
                <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
            </a>
            <a id="m_4" href="{{ url_for('home.loginlog') }}" class="list-group-item">
                <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
            </a>
            <a id="m_5" href="{{ url_for('home.moviecol') }}" class="list-group-item">
                <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
            </a>
        </div>
    </div>